languageCode = "ja"
title = "オトナのプログラミング勉強会ブログ"
baseurl = "http://otona.pro/"
theme = "vienna"

[params]
	facebook = "オトナのプログラミング勉強会-1343421652358699"
	contact = "mailto:info@otona.pro"
	subtitle = "熊本のプログラミング勉強会"
	bio = "熊本で月2回開催されるオトナのプログラミングの勉強会ブログです"
